#ifndef VCAST_NEVER_STUB_EXTERNS
/* Begin defined extern variables */

/* INITIALIZATION_OBJECTS_USER_CODE "1" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "1" */
s_rb_EEPROMStructPD_buff_g EEPROM_Struct_PD 
/* INITIALIZATION_CODE_USER_CODE "1" */

/* INITIALIZATION_CODE_USER_CODE_END "1" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "2" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "2" */
unsigned char rb_Humidity_raw_g 
/* INITIALIZATION_CODE_USER_CODE "2" */

/* INITIALIZATION_CODE_USER_CODE_END "2" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "3" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "3" */
unsigned char rb_Humidity_g 
/* INITIALIZATION_CODE_USER_CODE "3" */

/* INITIALIZATION_CODE_USER_CODE_END "3" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "4" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "4" */
unsigned rw_Temperature_raw_g 
/* INITIALIZATION_CODE_USER_CODE "4" */

/* INITIALIZATION_CODE_USER_CODE_END "4" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "5" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "5" */
unsigned rw_DewPoint_g 
/* INITIALIZATION_CODE_USER_CODE "5" */

/* INITIALIZATION_CODE_USER_CODE_END "5" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "6" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "6" */
unsigned char rbi_HumTempComError_g 
/* INITIALIZATION_CODE_USER_CODE "6" */

/* INITIALIZATION_CODE_USER_CODE_END "6" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "7" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "7" */
s_rb_EEPROMStructAD_buff_g EEPROM_Struct_AD 
/* INITIALIZATION_CODE_USER_CODE "7" */

/* INITIALIZATION_CODE_USER_CODE_END "7" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "8" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "8" */
byte rb_WDG_BusTaskCounter_g 
/* INITIALIZATION_CODE_USER_CODE "8" */

/* INITIALIZATION_CODE_USER_CODE_END "8" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "9" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "9" */
union tLinIndicationBits uLinIndicationFlags 
/* INITIALIZATION_CODE_USER_CODE "9" */

/* INITIALIZATION_CODE_USER_CODE_END "9" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "10" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "10" */
union tLinConfirmationBits uLinConfirmationFlags 
/* INITIALIZATION_CODE_USER_CODE "10" */

/* INITIALIZATION_CODE_USER_CODE_END "10" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "11" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "11" */
byte rb_WakeupCounter_mg 
/* INITIALIZATION_CODE_USER_CODE "11" */

/* INITIALIZATION_CODE_USER_CODE_END "11" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "12" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "12" */
_c_RlsmCem_SerNrLin1Fr01_CEM_LIN1_buf RlsmCem_SerNrLin1Fr01_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "12" */

/* INITIALIZATION_CODE_USER_CODE_END "12" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "13" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "13" */
_c_RlsmCem_Lin1PartNrFr02_CEM_LIN1_buf RlsmCem_Lin1PartNrFr02_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "13" */

/* INITIALIZATION_CODE_USER_CODE_END "13" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "14" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "14" */
_c_RlsmCem_Lin1PartNrFr01_CEM_LIN1_buf RlsmCem_Lin1PartNrFr01_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "14" */

/* INITIALIZATION_CODE_USER_CODE_END "14" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "15" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "15" */
_c_RlsmCem_Lin1Fr03_CEM_LIN1_buf RlsmCem_Lin1Fr03_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "15" */

/* INITIALIZATION_CODE_USER_CODE_END "15" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "16" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "16" */
_c_RlsmCem_Lin1Fr02_CEM_LIN1_buf RlsmCem_Lin1Fr02_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "16" */

/* INITIALIZATION_CODE_USER_CODE_END "16" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "17" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "17" */
_c_RlsmCem_Lin1Fr01_CEM_LIN1_buf RlsmCem_Lin1Fr01_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "17" */

/* INITIALIZATION_CODE_USER_CODE_END "17" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "18" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "18" */
_c_CemCem_Lin1Fr06_CEM_LIN1_buf CemCem_Lin1Fr06_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "18" */

/* INITIALIZATION_CODE_USER_CODE_END "18" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "19" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "19" */
_c_CemCem_Lin1Fr05_CEM_LIN1_buf CemCem_Lin1Fr05_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "19" */

/* INITIALIZATION_CODE_USER_CODE_END "19" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "20" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "20" */
_c_CemCem_Lin1Fr04_CEM_LIN1_buf CemCem_Lin1Fr04_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "20" */

/* INITIALIZATION_CODE_USER_CODE_END "20" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "21" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "21" */
_c_CemCem_Lin1Fr03_CEM_LIN1_buf CemCem_Lin1Fr03_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "21" */

/* INITIALIZATION_CODE_USER_CODE_END "21" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "22" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "22" */
_c_CemCem_Lin1Fr02_CEM_LIN1_buf CemCem_Lin1Fr02_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "22" */

/* INITIALIZATION_CODE_USER_CODE_END "22" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "23" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "23" */
_c_CemCem_Lin1Fr01_CEM_LIN1_buf CemCem_Lin1Fr01_CEM_LIN1 
/* INITIALIZATION_CODE_USER_CODE "23" */

/* INITIALIZATION_CODE_USER_CODE_END "23" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "24" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "24" */
volatile Flag uF_VoltageStatus_g 
/* INITIALIZATION_CODE_USER_CODE "24" */

/* INITIALIZATION_CODE_USER_CODE_END "24" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "25" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "25" */
byte rb_InternalTemperature_g 
/* INITIALIZATION_CODE_USER_CODE "25" */

/* INITIALIZATION_CODE_USER_CODE_END "25" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "26" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "26" */
byte rb_ClockFreq_Error_cnt_g 
/* INITIALIZATION_CODE_USER_CODE "26" */

/* INITIALIZATION_CODE_USER_CODE_END "26" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "27" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "27" */
Flag uF_uC_Error_g 
/* INITIALIZATION_CODE_USER_CODE "27" */

/* INITIALIZATION_CODE_USER_CODE_END "27" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "28" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "28" */
Flag uF_Diagnose_pre_Flag 
/* INITIALIZATION_CODE_USER_CODE "28" */

/* INITIALIZATION_CODE_USER_CODE_END "28" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "29" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "29" */
unsigned char rub_RSIntermDelayInit 
/* INITIALIZATION_CODE_USER_CODE "29" */

/* INITIALIZATION_CODE_USER_CODE_END "29" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "30" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "30" */
unsigned char rb_LimitMemomryNoWiperReaction_g 
/* INITIALIZATION_CODE_USER_CODE "30" */

/* INITIALIZATION_CODE_USER_CODE_END "30" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "31" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "31" */
unsigned char rbi_WiperStarted_g 
/* INITIALIZATION_CODE_USER_CODE "31" */

/* INITIALIZATION_CODE_USER_CODE_END "31" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "32" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "32" */
unsigned char rb_LIN_SensitivityShift_g 
/* INITIALIZATION_CODE_USER_CODE "32" */

/* INITIALIZATION_CODE_USER_CODE_END "32" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "33" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "33" */
volatile RS_Flag RSStatus 
/* INITIALIZATION_CODE_USER_CODE "33" */

/* INITIALIZATION_CODE_USER_CODE_END "33" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "34" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "34" */
unsigned char rub_IntermDelayTime 
/* INITIALIZATION_CODE_USER_CODE "34" */

/* INITIALIZATION_CODE_USER_CODE_END "34" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "35" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "35" */
unsigned char rb_PotiStageFromBox_g 
/* INITIALIZATION_CODE_USER_CODE "35" */

/* INITIALIZATION_CODE_USER_CODE_END "35" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "36" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "36" */
unsigned rw_rain_intensitiy_g 
/* INITIALIZATION_CODE_USER_CODE "36" */

/* INITIALIZATION_CODE_USER_CODE_END "36" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "37" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "37" */
Flag uF_StatusRainsensor_mg 
/* INITIALIZATION_CODE_USER_CODE "37" */

/* INITIALIZATION_CODE_USER_CODE_END "37" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "38" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "38" */
Flag uF_StatusRainsensor2_mg 
/* INITIALIZATION_CODE_USER_CODE "38" */

/* INITIALIZATION_CODE_USER_CODE_END "38" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "39" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "39" */
byte rb_WiperSpeed_g 
/* INITIALIZATION_CODE_USER_CODE "39" */

/* INITIALIZATION_CODE_USER_CODE_END "39" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "40" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "40" */
byte rb_WiperSpeedAlt_g 
/* INITIALIZATION_CODE_USER_CODE "40" */

/* INITIALIZATION_CODE_USER_CODE_END "40" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "41" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "41" */
volatile Flag uF_LIN_DiagReq2_mg 
/* INITIALIZATION_CODE_USER_CODE "41" */

/* INITIALIZATION_CODE_USER_CODE_END "41" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "42" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "42" */
volatile Flag uF_Main_Flags_g 
/* INITIALIZATION_CODE_USER_CODE "42" */

/* INITIALIZATION_CODE_USER_CODE_END "42" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "43" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "43" */
byte rb_RS_LS_Error1_g 
/* INITIALIZATION_CODE_USER_CODE "43" */

/* INITIALIZATION_CODE_USER_CODE_END "43" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "44" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "44" */
byte rb_RS_LS_Error2_g 
/* INITIALIZATION_CODE_USER_CODE "44" */

/* INITIALIZATION_CODE_USER_CODE_END "44" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "45" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "45" */
byte rb_RainS_Error1_g 
/* INITIALIZATION_CODE_USER_CODE "45" */

/* INITIALIZATION_CODE_USER_CODE_END "45" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "46" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "46" */
byte rb_LightS_Error1_g 
/* INITIALIZATION_CODE_USER_CODE "46" */

/* INITIALIZATION_CODE_USER_CODE_END "46" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "47" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "47" */
unsigned rw_EEPROM_Address_to_Write_g 
/* INITIALIZATION_CODE_USER_CODE "47" */

/* INITIALIZATION_CODE_USER_CODE_END "47" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "48" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "48" */
byte rb_I2C_EEPROM_bytesToWrite_g 
/* INITIALIZATION_CODE_USER_CODE "48" */

/* INITIALIZATION_CODE_USER_CODE_END "48" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "49" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "49" */
byte rab_EEPROM_Bytes_toWrite_g[5] 
/* INITIALIZATION_CODE_USER_CODE "49" */

/* INITIALIZATION_CODE_USER_CODE_END "49" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "50" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "50" */
volatile Flag uF_E2ConfigErrorFlags_g 
/* INITIALIZATION_CODE_USER_CODE "50" */

/* INITIALIZATION_CODE_USER_CODE_END "50" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "51" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "51" */
byte rb_speed_in_kmh_g 
/* INITIALIZATION_CODE_USER_CODE "51" */

/* INITIALIZATION_CODE_USER_CODE_END "51" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "52" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "52" */
byte rb_LSPotiStage_g 
/* INITIALIZATION_CODE_USER_CODE "52" */

/* INITIALIZATION_CODE_USER_CODE_END "52" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "53" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "53" */
Flag uF_Check_lightsensor_g 
/* INITIALIZATION_CODE_USER_CODE "53" */

/* INITIALIZATION_CODE_USER_CODE_END "53" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "54" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "54" */
Flag uF_modi_lightsens_g 
/* INITIALIZATION_CODE_USER_CODE "54" */

/* INITIALIZATION_CODE_USER_CODE_END "54" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "55" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "55" */
Flag uF_LightInternalStatus_g 
/* INITIALIZATION_CODE_USER_CODE "55" */

/* INITIALIZATION_CODE_USER_CODE_END "55" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "56" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "56" */
unsigned rw_StandbyTimeOutCnt_g 
/* INITIALIZATION_CODE_USER_CODE "56" */

/* INITIALIZATION_CODE_USER_CODE_END "56" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "57" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "57" */
byte rb_ASIC_ALSx_ShortDetected_cnt_g 
/* INITIALIZATION_CODE_USER_CODE "57" */

/* INITIALIZATION_CODE_USER_CODE_END "57" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "58" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "58" */
byte rb_ASIC_ALSx_ShortDetected_Error_g 
/* INITIALIZATION_CODE_USER_CODE "58" */

/* INITIALIZATION_CODE_USER_CODE_END "58" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "59" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "59" */
Flag uF_ASIC_ControlFlags_g 
/* INITIALIZATION_CODE_USER_CODE "59" */

/* INITIALIZATION_CODE_USER_CODE_END "59" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "60" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "60" */
Flag uF_GainAdjustFlags_g 
/* INITIALIZATION_CODE_USER_CODE "60" */

/* INITIALIZATION_CODE_USER_CODE_END "60" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "61" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "61" */
Flag uF_ASIC_Error_Flags_g 
/* INITIALIZATION_CODE_USER_CODE "61" */

/* INITIALIZATION_CODE_USER_CODE_END "61" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "62" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "62" */
Flag uF_ASIC_Error_Flags1_g 
/* INITIALIZATION_CODE_USER_CODE "62" */

/* INITIALIZATION_CODE_USER_CODE_END "62" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "63" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "63" */
Flag uF_ASIC_Ctrl_Error_Flags_g 
/* INITIALIZATION_CODE_USER_CODE "63" */

/* INITIALIZATION_CODE_USER_CODE_END "63" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "64" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "64" */
unsigned rw_Solar_light16bit_1_g 
/* INITIALIZATION_CODE_USER_CODE "64" */

/* INITIALIZATION_CODE_USER_CODE_END "64" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "65" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "65" */
unsigned rw_Solar_light16bit_2_g 
/* INITIALIZATION_CODE_USER_CODE "65" */

/* INITIALIZATION_CODE_USER_CODE_END "65" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "66" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "66" */
ASIC_ALI_Meas_t ras_ASIC_MUX_MeasAD_g[9] 
/* INITIALIZATION_CODE_USER_CODE "66" */

/* INITIALIZATION_CODE_USER_CODE_END "66" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "67" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "67" */
byte rb_ASIC_initTimeout_g 
/* INITIALIZATION_CODE_USER_CODE "67" */

/* INITIALIZATION_CODE_USER_CODE_END "67" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "68" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "68" */
byte rb_VIref_ErrCnt_g 
/* INITIALIZATION_CODE_USER_CODE "68" */

/* INITIALIZATION_CODE_USER_CODE_END "68" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "69" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "69" */
byte rb_ASIC_SPI_ErrorCodeCnt_g 
/* INITIALIZATION_CODE_USER_CODE "69" */

/* INITIALIZATION_CODE_USER_CODE_END "69" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "70" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "70" */
byte rb_StaticNoValidAD_cnt_g 
/* INITIALIZATION_CODE_USER_CODE "70" */

/* INITIALIZATION_CODE_USER_CODE_END "70" */
;


/* INITIALIZATION_OBJECTS_USER_CODE "71" */
/* INITIALIZATION_OBJECTS_USER_CODE_END "71" */
unsigned rw_SPINoCommCounter_g 
/* INITIALIZATION_CODE_USER_CODE "71" */

/* INITIALIZATION_CODE_USER_CODE_END "71" */
;

/* End defined extern variables */
/* Begin defined static member variables */
/* End defined static member variables */
#endif /*VCAST_NEVER_STUB_EXTERNS*/
/* BEGIN PROTOTYPE STUBS */
unsigned char P_10_1_1

;
void sci_init(byte rb_WakeUpFrame_l)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_1
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_1
  if ( vcast_is_in_driver ) {
    P_10_1_1 = rb_WakeUpFrame_l;
    vCAST_COMMON_STUB_PROC_9( 10, 1, 2, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_1
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_1
  vCAST_USER_CODE_TIMER_START();
  return;
}


void Check_StartupActiveErrors(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_2
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_2
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 2, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_2
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_2
  vCAST_USER_CODE_TIMER_START();
  return;
}


unsigned char R_10_3;
byte get_rb_LightVetoCounter_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_3
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_3
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 3, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_3
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_3
  vCAST_USER_CODE_TIMER_START();
  return R_10_3;
}


unsigned R_10_4;
unsigned get_rw_Amb_light16bit_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_4
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_4
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 4, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_4
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_4
  vCAST_USER_CODE_TIMER_START();
  return R_10_4;
}


unsigned long R_10_5;
unsigned long get_rl_HUD_light32bit_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_5
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_5
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 5, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_5
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_5
  vCAST_USER_CODE_TIMER_START();
  return R_10_5;
}


unsigned R_10_6;
unsigned get_rw_IR_light16bit_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_6
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_6
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 6, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_6
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_6
  vCAST_USER_CODE_TIMER_START();
  return R_10_6;
}


unsigned char R_10_7;
byte get_rb_LightSignalErrorCnt_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_7
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_7
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 7, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_7
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_7
  vCAST_USER_CODE_TIMER_START();
  return R_10_7;
}


unsigned char R_10_8;
byte get_rb_VDD_LightSignalErrorCnt_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_8
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_8
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 8, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_8
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_8
  vCAST_USER_CODE_TIMER_START();
  return R_10_8;
}


unsigned char R_10_9;
byte get_rb_LEDx_LStop_error_cnt_g(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_9
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_9
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 9, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_9
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_9
  vCAST_USER_CODE_TIMER_START();
  return R_10_9;
}


void CopyRLSDataAsic(void)
{
  vCAST_USER_CODE_TIMER_STOP();
#define BEGINNING_OF_STUB_USER_CODE_10_10
#include "vcast_configure_stub.c"
#undef BEGINNING_OF_STUB_USER_CODE_10_10
  if ( vcast_is_in_driver ) {
    vCAST_COMMON_STUB_PROC_9( 10, 10, 1, 0 );
  } /* vcast_is_in_driver */
#define END_OF_STUB_USER_CODE_10_10
#include "vcast_configure_stub.c"
#undef END_OF_STUB_USER_CODE_10_10
  vCAST_USER_CODE_TIMER_START();
  return;
}


/* END PROTOTYPE STUBS */
