/* Undefine all field names (disable by setting VCAST_DO_NOT_UNDEF_FIELDS) */
#undef _c
#undef EEPROMStructPD
#undef _c
#undef EEPROMStructAD
#undef _c
#undef w
#undef _c
#undef w
#undef Bit
#undef AllBit
#undef Bit
#undef AllBit
#undef _c
#undef rlsmcem_sernrlin1fr01_cem_lin1
#undef _c
#undef rlsmcem_lin1partnrfr02_cem_lin1
#undef _c
#undef rlsmcem_lin1partnrfr01_cem_lin1
#undef _c
#undef rlsmcem_lin1fr03_cem_lin1
#undef _c
#undef rlsmcem_lin1fr02_cem_lin1
#undef _c
#undef rlsmcem_lin1fr01_cem_lin1
#undef _c
#undef cemcem_lin1fr06_cem_lin1
#undef _c
#undef cemcem_lin1fr05_cem_lin1
#undef _c
#undef cemcem_lin1fr04_cem_lin1
#undef _c
#undef cemcem_lin1fr03_cem_lin1
#undef _c
#undef cemcem_lin1fr02_cem_lin1
#undef _c
#undef cemcem_lin1fr01_cem_lin1
#undef Bit
#undef AllBit
#undef ProductionData_g
#undef EEKodierbyte2_g
#undef EEKodierbyte1_g
#undef EEKodierbyte0_g
#undef ALS1_4_Setting_g
#undef ALS5_6_INREC_Setting_g
#undef ASIC_DIAGV_g
#undef A_Factor_ALS1_g
#undef A_Factor_ALS2_g
#undef A_Factor_ALS3_g
#undef A_Factor_ALS4_g
#undef A_Factor_ALS5_g
#undef A_Factor_ALS6_g
#undef A_Factor_INREC_g
#undef B_Factor_Iref_Lo_Gain_Lo_g
#undef B_Factor_Iref_Lo_Gain_Hi_g
#undef B_Factor_Iref_Hi_Gain_Lo_g
#undef B_Factor_Iref_Hi_Gain_Hi_g
#undef CRC_Checksum_calibration_g
#undef Standby_rain_measurement_1_g
#undef Standby_rain_measurement_2_g
#undef Standby_rain_measurement_3_g
#undef Standby_rain_measurement_4_g
#undef Standby_rain_measurement_5_g
#undef Standby_rain_measurement_6_g
#undef ASIC_Sched_Config_g
#undef ASIC_LCTR_g
#undef NO_RAIN_PRESENT_THRSH_HB_g
#undef NO_RAIN_PRESENT_THRSH_LB_g
#undef STBY_REGV_Imbalance_g
#undef RSControlFlags
#undef EEPROM_Erase_Counter
#undef HardwareStand
#undef Produktionsdaten
#undef Fertigungsdatum
#undef Audi_HW_Partnumber
#undef NAD
#undef IDFSs_01
#undef IDRLSs_01
#undef IDBCM1_LIN1_01
#undef IDWWSs_01
#undef IDSOSES_01
#undef ASIC_Frame_01_g
#undef ASIC_Frame_02_g
#undef ASIC_Frame_03_g
#undef ASIC_Frame_04_g
#undef ASIC_RCTR_REG_g
#undef ASIC_RFCTR_REG_g
#undef Error_Active_1_g
#undef Error_Active_2_g
#undef Error_Active_3_g
#undef Erase_counter
#undef VariantID_g
#undef FunctionID_g
#undef IDERRDATA_01
#undef IDSPARE_01
#undef IDRLSs_02
#undef IDBCM1_LIN1_02
#undef HUD_Factor_g
#undef IDRLSs_03
#undef IDRLSs_04
#undef IDRLSs_05
#undef IDRLSs_06
#undef IDBCM1_LIN1_03
#undef IDBCM1_LIN1_04
#undef IDBCM1_LIN1_05
#undef HUD_MAX_Value
#undef HUD_MAX_Resolution
#undef PrametersStruct
#undef RS_GainSetupArray
#undef HALIOS_Clock_Control_Reg_g
#undef ACTR_Reg_g
#undef PCO_PI_Regulator_g
#undef ICO1H_g
#undef ICO1L_g
#undef ICO2H_g
#undef ICO2L_g
#undef FOSC_LEDUL_g
#undef INTCO_g
#undef StandbyTimout
#undef dec_st2_speicher
#undef RS_Sensitivity
#undef MaxOverwipeSensitivity
#undef StandbyModeScanTime_g
#undef RainNightBitThrs_g
#undef Amb_Base_Day_Threshold
#undef Amb_Base_Night_Threshold
#undef TunnelDebounceFactor
#undef Customer_FW_SWA_Scaling
#undef Customer_IR_SWA_Scaling
#undef FW_Base_Day_Threshold
#undef IR_Base_Day_Threshold
#undef FW_Base_Night_Threshold
#undef IR_Base_Night_Threshold
#undef Day_Delay
#undef Night_Delay
#undef AfterTunnelDelayOffs
#undef p_v_autobahn_on_off_g
#undef p_t_autobahn_delay_on_g
#undef Frontwaschen_Autobahndelay_g
#undef p_n_regenlichtschwelle_low_high_g
#undef p_n_regenlichtschwelle_Zeit_g
#undef TunnelThresholdScaling_g
#undef Amb_TunnelThresholdScaling_g
#undef spare
#undef Regulation48LightOnTime_g
#undef VeryBrightInTunnelDelay_g
#undef Combined_FW_AL_THRs_g
#undef DYN_COMP_CCD_MINUS_1_g
#undef DYN_COMP_CCD_MINUS_2_g
#undef maxTemperatureOffsett_g
#undef ASIC_AFSTHR_REG_g
#undef Diag_Request_Factor_g
#undef cb_inc_speicher_g
#undef I2C_Debug_Config_g
#undef Audi_SW_Partnumber
#undef wiperSpeedHysteresis
#undef Proj_Specific_config
#undef ALSx_Filter_g
#undef IrLightTunnelThreshodRng
#undef FwLightTunnelThresholdRng
#undef AmbLightTunnelThresholdRng
#undef TunWischVerzAktiv
#undef SHTErrorDebounceJitter
#undef SolarShadowCorrFactor1
#undef SolarShadowCorrFactor2
#undef E2_MaxSt2SignalLaenge
#undef SoftwareStand
#undef twilightToDarkTime
#undef darkToTwilightTime
#undef darkToTwilightThreshFW
#undef darkToTwilightThreshAMB
#undef twilightToDarkThreshFW
#undef twilightToDarkThreshAMB
#undef iceDetectionTemperature
#undef Regulation48ThresholdAmb_g
#undef Regulation48ThresholdFw_g
#undef Threshold_TempIceRisk
#undef upperTolerance_StartupWipe
#undef unused
#undef B0
#undef B1
#undef B2
#undef B3
#undef B4
#undef B5
#undef B6
#undef B7
#undef RLSMSerNoNr1_CEM_LIN1
#undef RLSMSerNoNr2_CEM_LIN1
#undef RLSMSerNoNr3_CEM_LIN1
#undef RLSMSerNoNr4_CEM_LIN1
#undef RLSMPartNo10Nr1_CEM_LIN1
#undef RLSMPartNo10Nr2_CEM_LIN1
#undef RLSMPartNo10Nr3_CEM_LIN1
#undef RLSMPartNo10Nr4_CEM_LIN1
#undef RLSMPartNo10Nr5_CEM_LIN1
#undef RLSMPartNo10EndSgn1_CEM_LIN1
#undef RLSMPartNo10EndSgn2_CEM_LIN1
#undef RLSMPartNo10EndSgn3_CEM_LIN1
#undef RLSMPartNoNr1_CEM_LIN1
#undef RLSMPartNoNr2_CEM_LIN1
#undef RLSMPartNoNr3_CEM_LIN1
#undef RLSMPartNoNr4_CEM_LIN1
#undef RLSMPartNoEndSgn1_CEM_LIN1
#undef RLSMPartNoEndSgn2_CEM_LIN1
#undef RLSMPartNoEndSgn3_CEM_LIN1
#undef SolarSnsrErr_CEM_LIN1
#undef RainSnsrDiagcRainSnsrHiVoltDetd_CEM_LIN1
#undef RainSnsrDiagcRainSnsrHiTDetd_CEM_LIN1
#undef LiOprnMod_CEM_LIN1
#undef RainDetected_CEM_LIN1
#undef unused0
#undef SolarSnsrLeValue_CEM_LIN1
#undef SolarSnsrRiValue_CEM_LIN1
#undef unused1
#undef unused2
#undef unused3
#undef unused4
#undef CmptFrntWindDewT_CEM_LIN1_0
#undef CmptFrntWindDewT_CEM_LIN1_1
#undef AmbIllmnFwdStsCntr_CEM_LIN1
#undef unused0
#undef AmbIllmnFwdStsAmblillmn2_CEM_LIN1
#undef AmbIllmnFwdStsChks_CEM_LIN1
#undef AmbIllmnFwdStsAmblillmn1_CEM_LIN1_0
#undef AmbIllmnFwdStsAmblillmn1_CEM_LIN1_1
#undef CmptFrntWindTErr_CEM_LIN1
#undef RelHumSnsrErr_CEM_LIN1
#undef CmptFrntWindT_CEM_LIN1_0
#undef CmptFrntWindT_CEM_LIN1_1
#undef RelHumSnsrRelHum_CEM_LIN1
#undef AutWinWipgCmd_CEM_LIN1
#undef HudSnsrErrParChk_CEM_LIN1
#undef HudSnsrErrSnsrErr_CEM_LIN1
#undef unused0
#undef RainLi_CEM_LIN1
#undef RainSnsrErrCalErrActv_CEM_LIN1
#undef RainSnsrErrCalErr_CEM_LIN1
#undef RainSnsrErrRainDetnErr_CEM_LIN1
#undef RainSnsrErrRainDetnErrActv_CEM_LIN1
#undef WipgAutFrntMod_CEM_LIN1
#undef unused1
#undef ErrRespRLSM_CEM_LIN1
#undef unused2
#undef TwliBriRawQf_CEM_LIN1
#undef TwliBriRawTwliBriRaw_CEM_LIN1_0
#undef TwliBriRawTwliBriRaw_CEM_LIN1_1
#undef unused3
#undef OutdBriChks_CEM_LIN1
#undef OutdBriSts_CEM_LIN1
#undef unused4
#undef unused0
#undef WiprActv_CEM_LIN1
#undef WiprInPrkgPosnLo_CEM_LIN1
#undef WiprInWipgAr_CEM_LIN1
#undef WshngCycActv_CEM_LIN1
#undef unused0
#undef VehMtnStCntr_CEM_LIN1
#undef VehMtnStVehMtnSt_CEM_LIN1
#undef VehMtnStChks_CEM_LIN1
#undef unused1
#undef EnaOfflineMonitor_CEM_LIN1
#undef unused2
#undef unused3
#undef unused4
#undef unused5
#undef unused6
#undef unused0
#undef unused1
#undef unused2
#undef unused3
#undef DoorDrvrSts_CEM_LIN1
#undef unused4
#undef unused5
#undef RainSnsrLiThd_CEM_LIN1
#undef unused6
#undef RainSnsrSnvtyForUsrSnvty0_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty1_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty2_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty3_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty4_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty5_CEM_LIN1
#undef RainSnsrSnvtyForUsrSnvty6_CEM_LIN1
#undef VehTyp_CEM_LIN1
#undef WindCorrnValAmb_CEM_LIN1
#undef WindCorrnValFrnt_CEM_LIN1
#undef WindCorrnValHud_CEM_LIN1
#undef FrqCfg_CEM_LIN1
#undef ReAdaptReq_CEM_LIN1
#undef unused0
#undef AmbTForVisy_CEM_LIN1
#undef unused0
#undef VehModMngtGlbSafe1FltEgyCnsWdSts_CEM_LIN1
#undef VehModMngtGlbSafe1CarModSts1_CEM_LIN1
#undef VehModMngtGlbSafe1CarModSubtypWdCarModSubtyp_CEM_LIN1
#undef VehModMngtGlbSafe1Chks_CEM_LIN1
#undef VehModMngtGlbSafe1EgyLvlElecMai_CEM_LIN1
#undef VehModMngtGlbSafe1Cntr_CEM_LIN1
#undef VehModMngtGlbSafe1PwrLvlElecMai_CEM_LIN1
#undef VehModMngtGlbSafe1EgyLvlElecSubtyp_CEM_LIN1
#undef VehModMngtGlbSafe1UsgModSts_CEM_LIN1
#undef VehModMngtGlbSafe1PwrLvlElecSubtyp_CEM_LIN1
#undef unused1
#undef VehSpdForWipg_CEM_LIN1
#undef WipgPwrActvnSafeWipgPwrAcsyModSafe_CEM_LIN1
#undef WipgPwrActvnSafeWipgPwrDrvgModSafe_CEM_LIN1
#undef RainSensActvn_CEM_LIN1
#undef WshrLvrPosnSafe_CEM_LIN1
#undef unused0
#undef WiprMotFrntLvrCmdSafeLvrInHiSpdPosnSafe_CEM_LIN1
#undef WiprMotFrntLvrCmdSafeLvrInLoSpdPosnSafe_CEM_LIN1
#undef WiprMotFrntLvrCmdSafeLvrInSnglStrokePos_CEM_LIN1
#undef WiprMotFrntLvrCmdSafeLvrInIntlPosn_CEM_LIN1
#undef HomeLinkEna_CEM_LIN1
#undef WiprMotIntlCmd_CEM_LIN1
#undef WiprPosnForSrvReq_CEM_LIN1
#undef unused1
#undef IntrMirrCmdIntrMirrDimSnvty_CEM_LIN1
#undef IntrMirrCmdDrvrSide_CEM_LIN1
#undef IntrMirrCmdIntrMirrWindHeatrCmpMag_CEM_LIN1
#undef IntrMirrCmdIntrMirrEna_CEM_LIN1
#undef IntrMirrCmdIntrMirrInhbDim_CEM_LIN1
#undef IntrMirrCmdIntrMirrDiagcRst_CEM_LIN1
#undef IntrMirrCmdIntrMirrAsyFanCmpMag_CEM_LIN1
#undef WiprMotFrntOffsAg_CEM_LIN1
#undef unused2
#undef B7
#undef B6
#undef B5
#undef B4
#undef B3
#undef B2
#undef B1
#undef B0
#undef ad
#undef avg
#undef b0
#undef b1
#undef b2
#undef b3
#undef b4
#undef b5
#undef b6
#undef b7
#undef b0
#undef b1
#undef b2
#undef b3
#undef b4
#undef b5
#undef b6
#undef b7
#undef b8
#undef b9
#undef b10
#undef b11
#undef b12
#undef b13
#undef b14
#undef b15
#undef Stufe1_OG
#undef Stufe1_UG
#undef Ep_St2_Epr_In_St2
#undef Schwelle_Schwall
#undef CW_AnsamlungAdditOffset
#undef dec_Int_Sp_off
#undef Dec_Stx_Speicher
#undef dec_Ovr_Speicher
#undef Empf_Faktor_ST2_Offs
#undef Max_Signallaenge
#undef rb_Stufe1_with_Int_og
#undef Nachwisch_4_ST1_min
#undef Nachwisch_3
#undef Nachwisch_2
#undef RSEmpfFactorScaling
#undef SchlierenFlag1
#undef sig_ans_schw_offs
